name: google_translate
description: Google Translate API for Dart. Dynamically Translate Between Thousands of Languages
version: 0.0.6

homepage: https://github.com/lpongetti/google_translate

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.3.1
  dio_cache_interceptor_hive_store: ^3.2.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

false_secrets:
  - "/example/lib/main.dart"
